# Generated by Django 2.0.6 on 2018-06-26 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20180626_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='slug',
        ),
    ]
